apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: selector
  name: selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selector
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selector
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
