apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.custom-api.example.org
spec:
  group: custom-api.example.org
  names:
    kind: xDatabase
    plural: xdatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
              engineType:
                type: string
              vpcName:
                type: string
              createVPC:
                type: boolean
              region:
                type: string            
              engine:
                type: string
              engineVersion:
                type: string
              clusterParameterGroup:
                type: string
              dbClusterParameterGroupFamily:
                type: string
              dbClusterInstanceClass:
                type: string
              storageEncrypted:
                type: boolean
              storageType:
                type: string
              storageSize:
                type: integer
              parameterGroup:
                type: string
              subnetGroup:
                type: string
              securityGroups:
                type: array
                items:
                  type: string
              tags:
                type: object
                additionalProperties:
                  type: string
              masterUsername:
                type: string
              masterPassword:
                type: string
              autoGeneratePassword:
                type: boolean
              databases:
                type: array
                items:
                  type: string
            required:
              - region
              # - engine
              # - engineVersion
              # - instanceClass
              # - storageEncrypted
              # - storageType
              # - storageSize
              # - parameterGroup
              # - subnetGroup
              # - securityGroups
              # - masterUsername
              # - masterPassword
              # - autoGeneratePassword
          status:
            description: A Status represents the observed state
            properties:
              share:
                description: Freeform field containing status information
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
  claimNames:
    kind: DatabaseClaim
    plural: databaseclaims