apiVersion: custom-api.example.org/v1alpha1
kind: xDatabase
metadata:
  name: my-rds
  # namespace: rds
spec:
  createVPC: true
  buckets:
    - mybucket
    - mybucket2
  region: us-east-1
  engine: aurora-postgresql
  engineVersion: "16"
  dbClusterInstanceClass: medium
  dbClusterParameterGroupFamily: aurora-postgresql16
  databases:
    - mydb