apiVersion: v1
kind: Pod
metadata:
  labels:
    run: logging
  name: logging
spec:
  containers:
  - image: nginx
    name: logging
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
      done