apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ui-pod
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: test-container
        image: nginx